port: 8080
profile: k8s

image:
  name: romanowalex/simple-backend
  version: v1.0

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 500m
    memory: 1024Mi

metrics:
  path: "/backend/manage/prometheus"
  username: management
  password: passwd