server:
  port: 8080
spring:
  application:
    name: simple-backend
  main.banner-mode: off
  mvc.servlet.path: /backend

management:
  endpoint:
    health.probes.enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure.include: info,health,loggers,prometheus
  health.diskspace.enabled: false
  endpoint.health.show-details: always
  info.git.mode: simple
  health:
    readinessstate.enabled: true
    livenessstate.enabled: true