apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: "{{ .Values.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: simple-backend
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "{{ .Values.metrics.path }}"
        prometheus.io/port: "{{ .Values.port }}"
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/version: "{{ .Values.image.version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: simple-backend
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: {{ .Release.Name }}
          imagePullPolicy: Always
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.profile }}"
          livenessProbe:
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /backend/manage/health/liveness
              port: {{ .Values.port }}
          readinessProbe:
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /backend/manage/health/readiness
              port: {{ .Values.port }}
          ports:
            - name: web
              containerPort: {{ .Values.port }}